dbt_datavault_ah:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: gdb66275
      user: SYS_45969
      role: S45969_DBT_ROLE
      warehouse: S45969_DBT_WH
      database: S45969_DBT_DB
      schema: S45969_DBT_SCHEMA
      threads: 4
